@server = https://jeffersononsihuay-ideal-fortnight-wwvjqwgxqq62gq6p-8080.preview.app.github.dev
@emp = {{server}}/api/employees
###
GET {{emp}}
###
POST {{emp}}
Content-Type: application/json

{
    "firstName": "Bilbo",
    "lastName": "Baggins",
    "description": "burglar"
}